from pet.utils.registry import Registry


BACKBONES = Registry()
FPN_BODY = Registry()
FCOS_HEADS = Registry()
RETINANET_HEADS = Registry()
ROI_CLS_HEADS = Registry()
ROI_CLS_OUTPUTS = Registry()
ROI_BOX_HEADS = Registry()
ROI_BOX_OUTPUTS = Registry()
ROI_CASCADE_HEADS = Registry()
ROI_CASCADE_OUTPUTS = Registry()
ROI_MASK_HEADS = Registry()
ROI_MASK_OUTPUTS = Registry()
ROI_GRID_HEADS = Registry()
ROI_GRID_OUTPUTS = Registry()
ROI_KEYPOINT_HEADS = Registry()
ROI_KEYPOINT_OUTPUTS = Registry()
ROI_PARSING_HEADS = Registry()
ROI_PARSING_OUTPUTS = Registry()
ROI_UV_HEADS = Registry()
ROI_UV_OUTPUTS = Registry()
ROI_SEMSEG_HEADS = Registry()
ROI_SEMSEG_OUTPUTS = Registry()
MASKIOU_HEADS = Registry()
MASKIOU_OUTPUTS = Registry()
